# Generated by Django 3.0.2 on 2020-01-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('post_title', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('publish', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish'), ('unpublish', 'Unpublish')], default='draft', max_length=124)),
                ('view_count', models.IntegerField()),
                ('publish_date', models.DateTimeField(auto_now=True)),
                ('author_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
