# Generated by Django 3.0.2 on 2020-01-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200121_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish'), ('unpublish', 'Unpublish')], default='draft', max_length=124),
        ),
    ]
