# Generated by Django 3.0.2 on 2020-01-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200122_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'allaboutfunctionview', 'verbose_name_plural': 'allaboutfunctionviews'},
        ),
    ]
