# Generated by Django 3.0.2 on 2020-01-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200124_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'all about function view', 'verbose_name_plural': 'all about function views'},
        ),
    ]
