# Generated by Django 3.0.2 on 2020-01-22 13:54

import allaboutmodels.vaildators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Must be a unique Name.', max_length=30, unique=True, verbose_name='Person Name')),
                ('email', models.CharField(blank=True, help_text='Must be a unique email.', max_length=240, null=True, validators=[allaboutmodels.vaildators.email_vaildator, allaboutmodels.vaildators.domain_vaildator], verbose_name='Person Email')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='About Yourself')),
                ('gender', models.CharField(choices=[('none', 'None'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='none', max_length=120)),
                ('number', models.IntegerField(default=0, verbose_name='Phone Number')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
    ]
