# Generated by Django 3.0.2 on 2020-01-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0002_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
